name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - sclafus
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

# Platform
  - type: dropdown
    attributes:
      label: Platform
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS 13
        - macOS 12
        - macOS 11
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other platform
      description: If you are using Linux or other platforms, tell us more to help you out
      placeholder: ex. Arch Linux on Sway, using linux-zen version x.y.z
    validations:
      required: false

# Photos & Videos
  - type: textarea
    attributes:
      label: Screenshots or videos
      description: Add screenshots or videos that show the bug here.
      placeholder: Drag and drop the screenshots/videos into this box.
    validations:
      required: false
